### PR TITLE
Handle deprecations in scipy

### PR DESCRIPTION
**Pull request by StuartLittlefair**
Conjugate and poly fit have been removed from scipy

### CODE REVIEW

**Comment by martinjohndyer** [comment]
For completeness, prior to v1.12 SciPy used to essentially have `from numpy import *` internally so you could access these NumPy functions. Now this has been removed you have to instead import from NumPy directly.

---

Incidentally, the `np.polyfit` function is itself no longer recommended (https://numpy.org/doc/stable/reference/generated/numpy.polyfit.html) in favour of `np.polynomial.Polynomial.fit()`, so it might be worth changing that too:

```
coeffs = polyfit(lra, tst, 2)
solution = -(-coeffs[1] / (2 * coeffs[0]))
```
to
```
coeffs = np.polynomial.Polynomial.fit(lra, tst, deg=2).convert()
solution = -(-coeffs[0] / (2 * coeffs[1]))
```
etc (**Note the order of the coefficients has changed!** - https://numpy.org/doc/stable/reference/routines.polynomials.html#transition-guide)

**Comment by jmccormac01** [comment]
Thanks guys, as polyfit is not recommended any longer ill move to Martin's suggestion. I'll do some tests and then try to get this out asap.

**Comment by astrofrog** [comment]
@jmccormac01 - just to check, have you had a chance to look into this? donuts is now broken with scipy 1.13 (released at the start of April).

**Comment by jmccormac01** [comment]
Hi guys, I've just pushed v0.4.0 which should fix this issue. I started dealing with np.polynomial.polyfit but the packaging/testing of this repo has rotten away, so I'm leaving it as np.polyfit for now. I need to find some time soon to repackage (removing all the astropy affiliated stuff) and fix the tests coverage etc.

**Pull request closed without merging**
