### PR TITLE
External data

### PR DESCRIPTION
**Pull request by mindriot101**
An attempt at starting to move the data out of the repository.

The tests use `astropy.utils.data.download_file` which can cache downloads. This caching needed to be set up with travis manually, but hopefully will work ok.

For the time being the data is hosted at warwick while we look into other hosting solutions.

The astropy tests require the `@remote_data` decorator and special test invocation.

We must remember to remove the files from the repo, mostly for size reasons (https://help.github.com/articles/remove-sensitive-data/)

### CODE REVIEW

**Comment by mindriot101** [comment]
One worry I have is that this data downloading may make the tests brittle. Hopefully with caching this will be ok, but we shall have to wait and see.

**Comment by mindriot101** [comment]
After discussion, we decided that until we release a full "point" version, a release that does not have "dev" in the name, we will keep the data packaged. We have not decided on the hosting endpoint for the data but we have these choices:

* S3
* Warwick
* James' personal hosting space

As each travis build is going to download this data 9 times, and we've not sured up the hosting situation, we shall leave the data in the repository.

**Comment by jmccormac01** [comment]
If we do what I suggested in #25 and make a new stable release we should find the hosting solution then.  I've put the 6 testing files on my websever. I tested grabbing them with wget and this worked fine:

```
~/Desktop                                                                                         
▶ wget www.jamesjmccormac.com/donuts/data/J17490840-003.fit
--2016-05-10 22:06:21--  http://www.jamesjmccormac.com/donuts/data/J17490840-003.fit
Resolving www.jamesjmccormac.com... 176.32.230.45
Connecting to www.jamesjmccormac.com|176.32.230.45|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2177280 (2.1M) [image/fits]
Saving to: 'J17490840-003.fit'

J17490840-003.fit        100%[=================================>]   2.08M  3.29MB/s    in 0.6s    

2016-05-10 22:06:22 (3.29 MB/s) - 'J17490840-003.fit' saved [2177280/2177280]
```

Maybe we can do this and #25 at the same time. I will open another pull request to change the background subtraction method also.

**Comment by mindriot101** [comment]
Just rebased this branch onto the latest devel getting ready for a merge

**Pull request merged**
